---
- name: Install required packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
  - git
  - unzip

- include_tasks: maven.yml
- include_tasks: gradle.yml

- name: Add jenkins repo
  yum_repository:
    name: Jenkins-stable
    description: Jenkins-stable
    baseurl: http://pkg.jenkins.io/redhat-stable
    gpgcheck: no

- name: Install jenkins package
  yum:
    name: jenkins
    state: present

- name: Copy config template
  template:
    src: jenkins
    dest: /etc/sysconfig
    owner: root
    group: root
    mode: 0600

- name: Copy service template
  template:
    src: jenkins.service
    dest: /usr/lib/systemd/system/systemd-jenkins.service
    owner: root
    group: root
    mode: 0644

- name: Create symlink to service script
  file:
    src: /usr/lib/systemd/system/systemd-jenkins.service
    dest: /etc/systemd/system/multi-user.target.wants/jenkins.service
    owner: root
    group: root
    mode: 0755
    state: link

- name: Create admin user directory
  file:
    path: "{{jenkins_home}}/users/admin"
    state: directory
    recurse: yes
    owner: "{{jenkins_user}}"
    group: "{{jenkins_user}}"

- name: Create secrets directory
  file:
    path: "{{jenkins_home}}/secrets"
    state: directory
    recurse: yes
    owner: "{{jenkins_user}}"
    group: "{{jenkins_user}}"

- name: Copy admin user template
  template:
    src: admin-config.xml
    dest: "{{jenkins_home}}/users/admin/config.xml"
    owner: "{{jenkins_user}}"
    group: "{{jenkins_user}}"
    mode: 0644

- name: Copy config files
  copy:
    src: "{{item}}"
    dest: "{{jenkins_home}}"
    owner: "{{jenkins_user}}"
    group: "{{jenkins_user}}"
    mode: 0644
  with_items:
    - jenkins.CLI.xml
    - slave-to-master-security-kill-switch

- name: Copy config templates
  template:
    src: "{{item}}"
    dest: "{{jenkins_home}}"
    owner: "{{jenkins_user}}"
    group: "{{jenkins_user}}"
    mode: 0644
  with_items:
    - config.xml
    - hudson.tasks.Maven.xml
    - hudson.plugins.gradle.Gradle.xml

- name: Start service
  service:
    name: jenkins
    state: restarted

- name: Wait for jenkins restart
  wait_for:
    path: /var/log/jenkins/jenkins.log
    search_regex: Jenkins is fully up and running

- name: Install plugins
  jenkins_plugin:
    params: "{{jenkins_params}}"
    name: "{{item}}"
    timeout: 30
    state: present
  with_items: "{{jenkins_plugins}}"

- name: Start service
  service:
    name: jenkins
    state: restarted

