---
- name: Download and uncompress archive
  unarchive:
    src: "http://www-us.apache.org/dist/maven/maven-3/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz"
    dest: "{{dev_tools_dir}}"
    remote_src: yes
    creates: "{{dev_tools_dir}}/apache-maven-{{maven_version}}"
- name: Set environment variables
  template:
    src: maven.sh
    dest: /etc/profile.d
    owner: root
    group: root
    mode: 0644
